[package]
name = "notflix-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
bb8 = "0.7.1"
bb8-diesel = "0.2.1"
diesel = { version = "1.4.4", features = ["sqlite"] }
serde = { version = "1.0.114", features = [ "derive" ] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
