[package]
name = "notflix-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bb8 = "0.7.1"
bb8-diesel = "0.2.1"
diesel = { version = "1.4.4", features = ["sqlite"] }
once_cell = "1.9.0"
regex = "1.5.4"
scan_fmt = "0.2.6"
serde = { version = "1.0.114", features = [ "derive" ] }
serde_json = "1.0"
serde-xml-rs = "0.5.1"
tokio = { version = "1", features = ["full"] }
